//! Lua plugins for Rust applications.
//!
//! `stanchion` holds plugins up and fences them in: typed contracts and dependency
//! wiring on one side, sandboxing, capabilities and signatures on the other.
//!
//! This crate is a facade. Each layer is a separate crate so its cost stays optional —
//! `sigstore-verify` alone pulls a large dependency graph — and this one re-exports
//! them behind features:
//!
//! | Feature | Re-exports |
//! | --- | --- |
//! | *(always)* | [`stanchion_core`]: [`macro@lua_class`], [`LuaClass`], [`LuaObject`], [`BoxFuture`] |
//! | `registry` | [`registry`]: manifests, sandboxing, capabilities, reload |
//! | `luarocks` | [`registry::rocks`]: LuaRocks declarations |
//! | `signatures` | [`registry::signature`]: digests and the verifier seam |
//! | `sigstore-verify` | [`sigstore`]: keyless verification |
//! | `remote` | [`remote`]: out-of-process hosting |
//!
//! Code generated by [`macro@lua_class`] refers to `::stanchion`, so use the macro
//! through this crate rather than against `stanchion-core` directly.
//!
//! ```ignore
//! use stanchion::{lua_class, mlua::Result};
//!
//! #[lua_class]
//! pub trait Greeter {
//!     fn new(greeting: String) -> Result<Self>;
//!     fn greet(&self, who: String) -> Result<String>;
//! }
//! ```

// Re-exported at the root because generated code names these paths.
pub use stanchion_core::{
    BoxFuture, LuaClass, LuaHandle, LuaObject, MaybeSend, MaybeSync, __private, load_class,
    lua_class, mlua,
};

/// The contract layer, in full.
pub use stanchion_core as core;

/// Discovering, loading and sandboxing plugins.
#[cfg(feature = "registry")]
pub use stanchion_registry as registry;

/// Running plugins in a separate process.
#[cfg(feature = "remote")]
pub use stanchion_remote as remote;

/// Sigstore-backed signature verification.
#[cfg(feature = "sigstore-verify")]
pub use stanchion_sigstore as sigstore;
