//! Lua plugins for Rust applications.
//!
//! `stanchion` holds plugins up and fences them in.
//!
//! This crate is a facade. Each layer is a separate crate so its cost stays
//! optional, and this one re-exports them behind features:
//!
//! | Feature | Re-exports |
//! | --- | --- |
//! | *(always)* | [`abi`]: errors, values, limits, manifests, backend traits |
//! | `registry` | [`registry`]: manifests, sandboxing, capabilities, reload |
//! | `luarocks` | [`registry::rocks`]: LuaRocks declarations |
//! | `signatures` | [`registry::DirectoryDigest`] and [`registry::PluginVerifier`]: digests and the verifier seam |
//! | `sigstore-verify` | [`sigstore`]: keyless verification |
//! | `remote` | [`remote`]: out-of-process hosting |
//! | `distribution` | [`dist`]: packaging, an index, and pinned installs |
//! | `distribution-client` | the HTTPS half of [`dist`]: an index and package fetching |
//! | `index-server` | [`index_server`]: serving an index, framework-neutral |
//!
//! The Lua trait stack (`lua_class` macro, `LuaClass`, `LuaObject`, `LuaHandle`)
//! lives in `stanchion-lua` and is **not** re-exported here. Code generated by
//! `lua_class` refers to `::stanchion_lua`, so depend on `stanchion-lua`
//! directly when you use the macro.

// The Lua contract stack lives in stanchion-lua; this facade does not re-export it.

/// The runtime-agnostic vocabulary: [`abi::Error`], [`abi::Value`],
/// [`abi::ResourceLimits`], [`abi::Manifest`] and the backend traits.
///
/// Unconditional and unfeatured, because every other layer hands these types back.
/// They used to be reachable only by depending on `stanchion-abi` directly, which
/// contradicted this crate's whole premise of being the one dependency you add.
pub use stanchion_abi as abi;

/// Discovering, loading and sandboxing plugins.
#[cfg(feature = "registry")]
pub use stanchion_registry as registry;

/// Packaging, publishing and installing plugins.
#[cfg(feature = "distribution")]
pub use stanchion_dist as dist;

/// Serving a plugin index over HTTP.
#[cfg(feature = "index-server")]
pub use stanchion_index as index_server;

/// Running plugins in a separate process.
#[cfg(feature = "remote")]
pub use stanchion_remote as remote;

/// Sigstore-backed signature verification.
#[cfg(feature = "sigstore-verify")]
pub use stanchion_sigstore as sigstore;
