[package]
name = "stanchion-uniffi"
description = "Kotlin and Swift bindings for stanchion, generated with UniFFI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "stanchion_uniffi"
crate-type = ["cdylib", "rlib"]

[dependencies]
stanchion-ffi = { workspace = true, features = ["async", "signatures"] }
uniffi = { version = "0.32", features = ["tokio", "cli"] }
thiserror = "2"


[features]
default = ["lua54", "vendored"]
lua54 = ["stanchion-ffi/lua54"]
lua53 = ["stanchion-ffi/lua53"]
luajit = ["stanchion-ffi/luajit"]
luau = ["stanchion-ffi/luau"]
vendored = ["stanchion-ffi/vendored"]

[lints]
workspace = true
