"""Type stubs for the compiled module."""

from __future__ import annotations

import builtins
from collections.abc import Callable, Mapping, Sequence
from os import PathLike
from typing import Any

StrPath = str | PathLike[str]

# A value that can cross into Lua, and one that can come back.
Value = None | bool | int | float | str | Sequence["Value"] | Mapping[str, "Value"]

class StanchionError(Exception): ...
class UnknownPluginError(StanchionError): ...
class PluginError(StanchionError): ...
class LuaError(StanchionError): ...
class ConfigError(StanchionError): ...
class CapabilityError(StanchionError): ...
class ReentrantError(StanchionError): ...

class CapabilityCall:
    """A plugin reaching back into Python through a granted capability."""

    @property
    def plugin(self) -> str: ...
    @property
    def capability(self) -> str: ...
    @property
    def grant(self) -> Value:
        """The parameters policy approved, which may be narrower than requested."""

    @property
    def args(self) -> list[Any]: ...

class CapabilityRequest:
    """What a plugin asked for, before any policy ran."""

    @property
    def plugin(self) -> str: ...
    @property
    def capability(self) -> str: ...
    @property
    def params(self) -> Value: ...
    @property
    def optional(self) -> bool: ...
    @property
    def signer(self) -> str:
        """Who signed the plugin, or ``"unsigned"``."""

class Decision:
    """A policy's answer to one request."""

    @staticmethod
    def grant() -> Decision: ...
    @staticmethod
    def grant_with(params: Mapping[str, Value]) -> Decision: ...
    @staticmethod
    def deny(reason: str) -> Decision: ...

class Failure:
    @property
    def plugin(self) -> str: ...
    @property
    def reason(self) -> str: ...

class LoadReport:
    @property
    def loaded(self) -> list[str]: ...
    @property
    def failures(self) -> list[Failure]: ...
    @property
    def is_clean(self) -> bool: ...

class PluginInfo:
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str | None: ...
    @property
    def granted(self) -> list[str]: ...
    @property
    def signer(self) -> str: ...

class AuditEntry:
    @property
    def plugin(self) -> str: ...
    @property
    def capabilities(self) -> list[str]: ...
    @property
    def signer(self) -> str: ...

class Outcome:
    @property
    def plugin(self) -> str: ...
    @property
    def value(self) -> Any | None: ...
    @property
    def error(self) -> str | None: ...

Provider = Callable[[CapabilityCall], Value]
Policy = Callable[[CapabilityRequest], Decision]

class Stanchion:
    """A registry of Lua plugins."""

    def __init__(
        self,
        *,
        plugins: StrPath | None = None,
        capabilities: Mapping[str, Provider] | None = None,
        policy: Policy | None = None,
        allow: Sequence[str] | None = None,
        libs: Sequence[str] | None = None,
        deny: Sequence[str] | None = None,
        memory_limit: int | None = None,
        instruction_limit: int | None = None,
        shared: bool = False,
        require_signatures: bool = False,
    ) -> None: ...
    @staticmethod
    def from_config_file(
        path: StrPath,
        *,
        capabilities: Mapping[str, Provider] | None = None,
        policy: Policy | None = None,
    ) -> Stanchion: ...
    def load(self, root: StrPath | None = None) -> LoadReport: ...
    def audit(self, root: StrPath | None = None) -> builtins.list[AuditEntry]: ...
    def list(self) -> builtins.list[PluginInfo]: ...
    def names(self) -> builtins.list[str]: ...
    def call(self, plugin: str, method: str, *args: Value) -> Any: ...
    def dispatch(self, method: str, *args: Value) -> builtins.list[Outcome]: ...
    async def call_async(self, plugin: str, method: str, *args: Value) -> Any: ...
    async def dispatch_async(self, method: str, *args: Value) -> builtins.list[Outcome]: ...
    def reload(self, plugin: str) -> None: ...
    def revoke(self, plugin: str, capability: str) -> bool: ...
    @property
    def isolation(self) -> str:
        """``"shared"`` or ``"per-plugin"``."""

    def __len__(self) -> int: ...
