//! Attribute macro backing [`stanchion`](https://docs.rs/stanchion).
//!
//! Generated code refers to `::stanchion`, so the macro is meant to be used through
//! the facade crate rather than against `stanchion-core` directly.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::spanned::Spanned;
use syn::visit_mut::VisitMut;
use syn::{
    Attribute, Error, FnArg, Ident, ItemTrait, Pat, PathArguments, ReturnType, TraitItem,
    TraitItemFn, Type, TypePath,
};

mod parse;

use parse::{ClassArgs, MethodKind, MethodOpts};

/// Binds a Lua class to a Rust trait.
///
/// Applied to a trait, it generates a class handle, an instance handle, and an impl of
/// the trait that delegates to the Lua object. See the crate docs of `mlua-plugin`.
#[proc_macro_attribute]
pub fn lua_class(args: TokenStream, input: TokenStream) -> TokenStream {
    let args = match ClassArgs::parse(args.into()) {
        Ok(args) => args,
        Err(err) => return err.to_compile_error().into(),
    };
    let item = syn::parse_macro_input!(input as ItemTrait);
    match expand(args, item) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// A single trait method, classified and ready to emit.
struct Method {
    sig_attrs: Vec<Attribute>,
    cfg_attrs: Vec<Attribute>,
    ident: Ident,
    lua_name: String,
    args: Vec<(Ident, Type)>,
    ret: Type,
    is_async: bool,
    takes_self: bool,
    kind: MethodKind,
}

fn expand(args: ClassArgs, item: ItemTrait) -> syn::Result<TokenStream2> {
    if !item.generics.params.is_empty() || item.generics.where_clause.is_some() {
        return Err(Error::new(
            item.generics.span(),
            "#[lua_class] does not support generic traits: a Lua class has no type parameters",
        ));
    }

    let trait_ident = item.ident.clone();
    let vis = item.vis.clone();
    let class_ident = args
        .class
        .clone()
        .unwrap_or_else(|| format_ident!("{}Class", trait_ident));
    let handle_ident = args
        .handle
        .clone()
        .unwrap_or_else(|| format_ident!("{}Handle", trait_ident));
    let class_name = args
        .lua_name
        .clone()
        .unwrap_or_else(|| trait_ident.to_string());

    let mut methods = Vec::new();
    let mut passthrough = Vec::new();
    for item in &item.items {
        match item {
            TraitItem::Fn(func) => methods.push(parse_method(func, &handle_ident)?),
            other => passthrough.push(other.clone()),
        }
    }

    let (class_fns, instance_fns): (Vec<_>, Vec<_>) = methods.iter().partition(|m| !m.takes_self);

    let required_functions = required_pushes(&class_fns);
    let required_methods = required_pushes(&instance_fns);

    let trait_items = instance_fns.iter().map(|m| trait_signature(m));
    let instance_impls = instance_fns
        .iter()
        .map(|m| instance_body(m))
        .collect::<syn::Result<Vec<_>>>()?;
    let class_impls = class_fns
        .iter()
        .map(|m| class_body(m))
        .collect::<syn::Result<Vec<_>>>()?;

    let trait_attrs = &item.attrs;
    let trait_doc_note = format!(
        "\n\nGenerated by `#[lua_class]`. [`{handle_ident}`] implements this by delegating \
         to a Lua object; [`{class_ident}`] constructs those objects."
    );
    let class_doc = format!("Handle to the Lua class table `{class_name}`.");
    let handle_doc = format!("Handle to an instance of the Lua class `{class_name}`.");
    let handle_str = handle_ident.to_string();
    let class_str = class_ident.to_string();

    Ok(quote! {
        #(#trait_attrs)*
        #[doc = #trait_doc_note]
        #vis trait #trait_ident: ::stanchion::MaybeSend + ::stanchion::MaybeSync {
            #(#passthrough)*
            #(#trait_items)*
        }

        #[doc = #class_doc]
        #[derive(Clone, Debug)]
        #vis struct #class_ident {
            handle: ::stanchion::LuaHandle,
        }

        impl #class_ident {
            #(#class_impls)*
        }

        impl ::stanchion::LuaClass for #class_ident {
            const CLASS_NAME: &'static str = #class_name;
            type Instance = #handle_ident;

            fn required_functions() -> ::std::vec::Vec<&'static str> {
                let mut __names = ::std::vec::Vec::new();
                #(#required_functions)*
                __names
            }

            fn from_handle(
                handle: ::stanchion::LuaHandle,
            ) -> ::stanchion::mlua::Result<Self> {
                ::stanchion::__private::require_handle_functions(
                    &handle,
                    #class_str,
                    &<Self as ::stanchion::LuaClass>::required_functions(),
                )?;
                Ok(Self { handle })
            }

            fn handle(&self) -> &::stanchion::LuaHandle {
                &self.handle
            }
        }

        impl ::stanchion::mlua::FromLua for #class_ident {
            fn from_lua(
                value: ::stanchion::mlua::Value,
                _lua: &::stanchion::mlua::Lua,
            ) -> ::stanchion::mlua::Result<Self> {
                let handle = ::stanchion::__private::expect_handle(value, #class_str)?;
                <Self as ::stanchion::LuaClass>::from_handle(handle)
            }
        }

        #[doc = #handle_doc]
        #[derive(Clone, Debug)]
        #vis struct #handle_ident {
            handle: ::stanchion::LuaHandle,
        }

        impl ::stanchion::LuaObject for #handle_ident {
            fn required_methods() -> ::std::vec::Vec<&'static str> {
                let mut __names = ::std::vec::Vec::new();
                #(#required_methods)*
                __names
            }

            fn from_handle(
                handle: ::stanchion::LuaHandle,
            ) -> ::stanchion::mlua::Result<Self> {
                ::stanchion::__private::require_handle_functions(
                    &handle,
                    #handle_str,
                    &<Self as ::stanchion::LuaObject>::required_methods(),
                )?;
                Ok(Self { handle })
            }

            fn handle(&self) -> &::stanchion::LuaHandle {
                &self.handle
            }

            fn into_handle(self) -> ::stanchion::LuaHandle {
                self.handle
            }
        }

        impl ::stanchion::mlua::FromLua for #handle_ident {
            fn from_lua(
                value: ::stanchion::mlua::Value,
                _lua: &::stanchion::mlua::Lua,
            ) -> ::stanchion::mlua::Result<Self> {
                let handle = ::stanchion::__private::expect_handle(value, #handle_str)?;
                <Self as ::stanchion::LuaObject>::from_handle(handle)
            }
        }

        impl #trait_ident for #handle_ident {
            #(#instance_impls)*
        }
    })
}

/// Classifies one trait method and normalises its pieces.
fn parse_method(func: &TraitItemFn, handle: &Ident) -> syn::Result<Method> {
    if func.default.is_some() {
        return Err(Error::new(
            func.span(),
            "#[lua_class] methods cannot have a default body: the body comes from Lua",
        ));
    }

    let (opts, sig_attrs) = MethodOpts::parse(&func.attrs)?;
    let sig = &func.sig;

    let mut inputs = sig.inputs.iter();
    // Peek through a clone so the receiver, if any, is consumed without a second match.
    let receiver = match inputs.clone().next() {
        Some(FnArg::Receiver(receiver)) => {
            inputs.next();
            Some(receiver)
        }
        _ => None,
    };
    let takes_self = receiver.is_some();
    if let Some(receiver) = receiver
        && (receiver.reference.is_none() || receiver.mutability.is_some())
    {
        return Err(Error::new(
            receiver.span(),
            "#[lua_class] methods must take `&self`: Lua objects are shared handles",
        ));
    }

    let mut args = Vec::new();
    for input in inputs {
        let arg = match input {
            FnArg::Typed(arg) => arg,
            FnArg::Receiver(receiver) => {
                return Err(Error::new(receiver.span(), "unexpected receiver"));
            }
        };
        let ident = match &*arg.pat {
            Pat::Ident(pat) => pat.ident.clone(),
            other => {
                return Err(Error::new(
                    other.span(),
                    "#[lua_class] arguments must be plain identifiers",
                ));
            }
        };
        let mut ty = (*arg.ty).clone();
        ReplaceSelf { with: handle }.visit_type_mut(&mut ty);
        args.push((ident, ty));
    }

    let ret = match &sig.output {
        ReturnType::Type(_, ty) => {
            let mut ty = (**ty).clone();
            ReplaceSelf { with: handle }.visit_type_mut(&mut ty);
            ty
        }
        ReturnType::Default => {
            return Err(Error::new(
                sig.span(),
                "#[lua_class] methods need an explicit `-> Result<..>` return type, \
                 over `mlua::Error` or any error type converting from it",
            ));
        }
    };

    let cfg_attrs: Vec<Attribute> = sig_attrs
        .iter()
        .filter(|attr| attr.path().is_ident("cfg"))
        .cloned()
        .collect();

    let kind = MethodKind::classify(&opts, takes_self, args.len(), &sig.ident, sig.span())?;
    let lua_name = opts
        .name
        .clone()
        .unwrap_or_else(|| kind.default_name(&sig.ident));

    if opts.optional && !returns_option(&ret) {
        return Err(Error::new(
            ret.span(),
            "optional methods must return `Result<Option<..>, _>`: \
             a missing Lua method yields `Ok(None)`",
        ));
    }

    Ok(Method {
        sig_attrs,
        cfg_attrs,
        ident: sig.ident.clone(),
        lua_name,
        args,
        ret,
        is_async: sig.asyncness.is_some(),
        takes_self,
        kind,
    })
}

/// One `#[cfg]`-gated push per required Lua key, so a method compiled out of the trait
/// is also dropped from the list its handle validates against.
fn required_pushes(methods: &[&Method]) -> Vec<TokenStream2> {
    methods
        .iter()
        .filter(|m| m.kind.is_required())
        .map(|m| {
            let cfg_attrs = &m.cfg_attrs;
            let name = &m.lua_name;
            quote! {
                #(#cfg_attrs)*
                __names.push(#name);
            }
        })
        .collect()
}

/// The method signature as it appears in the generated trait.
fn trait_signature(method: &Method) -> TokenStream2 {
    let Method {
        sig_attrs,
        ident,
        args,
        ret,
        is_async,
        ..
    } = method;
    let params = args.iter().map(|(ident, ty)| quote!(#ident: #ty));
    if *is_async {
        quote! {
            #(#sig_attrs)*
            fn #ident(&self #(, #params)*) -> ::stanchion::BoxFuture<'_, #ret>;
        }
    } else {
        quote! {
            #(#sig_attrs)*
            fn #ident(&self #(, #params)*) -> #ret;
        }
    }
}

/// The trait impl body for an instance method.
fn instance_body(method: &Method) -> syn::Result<TokenStream2> {
    let Method {
        cfg_attrs,
        ident,
        args,
        ret,
        is_async,
        ..
    } = method;
    let params = args.iter().map(|(ident, ty)| quote!(#ident: #ty));
    let table_expr = if *is_async {
        quote!(&__handle)
    } else {
        quote!(__handle)
    };
    let body = call_expr(method, table_expr)?;

    Ok(if *is_async {
        quote! {
            #(#cfg_attrs)*
            fn #ident(&self #(, #params)*) -> ::stanchion::BoxFuture<'_, #ret> {
                let __handle = ::core::clone::Clone::clone(&self.handle);
                ::std::boxed::Box::pin(async move { #body })
            }
        }
    } else {
        quote! {
            #(#cfg_attrs)*
            fn #ident(&self #(, #params)*) -> #ret {
                let __handle = &self.handle;
                #body
            }
        }
    })
}

/// The inherent impl body for a class-level function.
fn class_body(method: &Method) -> syn::Result<TokenStream2> {
    let Method {
        sig_attrs,
        ident,
        args,
        ret,
        is_async,
        ..
    } = method;
    let params = args.iter().map(|(ident, ty)| quote!(#ident: #ty));
    let table_expr = if *is_async {
        quote!(&__handle)
    } else {
        quote!(__handle)
    };
    let body = call_expr(method, table_expr)?;

    Ok(if *is_async {
        quote! {
            #(#sig_attrs)*
            pub fn #ident(&self #(, #params)*) -> ::stanchion::BoxFuture<'_, #ret> {
                let __handle = ::core::clone::Clone::clone(&self.handle);
                ::std::boxed::Box::pin(async move { #body })
            }
        }
    } else {
        quote! {
            #(#sig_attrs)*
            pub fn #ident(&self #(, #params)*) -> #ret {
                let __handle = &self.handle;
                #body
            }
        }
    })
}

/// The delegation expression, given an expression naming the backing table.
fn call_expr(method: &Method, table: TokenStream2) -> syn::Result<TokenStream2> {
    let name = &method.lua_name;
    let arg_idents: Vec<&Ident> = method.args.iter().map(|(ident, _)| ident).collect();
    let tuple = quote!((#(#arg_idents,)*));

    Ok(match method.kind {
        // Every direct return converts its error, so a method may return any
        // `Result<T, E>` with `E: From<mlua::Error>`. For `mlua::Result` itself the
        // conversion is the blanket `impl<T> From<T> for T`, so it costs nothing.
        MethodKind::FieldGet => quote! {
            ::core::result::Result::map_err(
                ::stanchion::LuaHandle::get(#table, #name),
                ::core::convert::From::from,
            )
        },
        MethodKind::FieldSet => {
            let Some(value) = arg_idents.first() else {
                return Err(Error::new(
                    method.ident.span(),
                    "a `field` setter needs exactly one argument",
                ));
            };
            quote! {
                ::core::result::Result::map_err(
                    ::stanchion::LuaHandle::set(#table, #name, #value),
                    ::core::convert::From::from,
                )
            }
        }
        MethodKind::Method { optional: false } if method.is_async => quote! {
            ::core::result::Result::map_err(
                ::stanchion::LuaHandle::call_async_method(#table, #name, #tuple).await,
                ::core::convert::From::from,
            )
        },
        MethodKind::Method { optional: false } => quote! {
            ::core::result::Result::map_err(
                ::stanchion::LuaHandle::call_method(#table, #name, #tuple),
                ::core::convert::From::from,
            )
        },
        MethodKind::Function { optional: false } if method.is_async => quote! {
            ::core::result::Result::map_err(
                ::stanchion::LuaHandle::call_async_function(#table, #name, #tuple).await,
                ::core::convert::From::from,
            )
        },
        MethodKind::Function { optional: false } => quote! {
            ::core::result::Result::map_err(
                ::stanchion::LuaHandle::call_function(#table, #name, #tuple),
                ::core::convert::From::from,
            )
        },
        // Optional methods resolve the function by hand so a missing key is `Ok(None)`
        // rather than an error from `call_method`.
        MethodKind::Method { optional: true } | MethodKind::Function { optional: true } => {
            let receiver = match method.kind {
                // A hand-resolved optional method still needs `self` passed, and a
                // handle is not itself a Lua value.
                MethodKind::Method { .. } => quote!(::stanchion::LuaHandle::to_value(#table),),
                _ => quote!(),
            };
            let call = if method.is_async {
                quote!(__function.call_async((#receiver #(#arg_idents,)*)).await?)
            } else {
                quote!(__function.call((#receiver #(#arg_idents,)*))?)
            };
            quote! {
                match ::stanchion::__private::optional_function(#table, #name)? {
                    ::core::option::Option::Some(__function) => {
                        ::core::result::Result::Ok(::core::option::Option::Some(#call))
                    }
                    ::core::option::Option::None => {
                        ::core::result::Result::Ok(::core::option::Option::None)
                    }
                }
            }
        }
    })
}

/// True when `ty` is a path ending in `Result<Option<..>>`.
fn returns_option(ty: &Type) -> bool {
    let Type::Path(TypePath { path, .. }) = ty else {
        return false;
    };
    let Some(last) = path.segments.last() else {
        return false;
    };
    let PathArguments::AngleBracketed(generics) = &last.arguments else {
        return false;
    };
    let Some(syn::GenericArgument::Type(Type::Path(inner))) = generics.args.first() else {
        return false;
    };
    inner
        .path
        .segments
        .last()
        .is_some_and(|segment| segment.ident == "Option")
}

/// Rewrites `Self` to the generated instance type, so constructors can say `-> Result<Self>`.
struct ReplaceSelf<'a> {
    with: &'a Ident,
}

impl VisitMut for ReplaceSelf<'_> {
    fn visit_type_path_mut(&mut self, node: &mut TypePath) {
        if node.qself.is_none() && node.path.is_ident("Self") {
            node.path = syn::Path::from(self.with.clone());
            return;
        }
        syn::visit_mut::visit_type_path_mut(self, node);
    }
}
