[package]
name = "stanchion-wasm"
description = "A WASM runtime backend for stanchion, built on wasmtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
exclude.workspace = true

[dependencies]
wasmtime = "49.0.2"
stanchion-abi = { workspace = true }

[lints]
workspace = true